export interface Product {
  id: number;
  name: string;
  description: string;
  price: string;
  category: 'necklace' | 'bracelet' | 'bangle';
  image: string;
  emoji: string;
  gradientFrom: string;
  gradientTo: string;
}

export interface ProductCategory {
  id: number;
  name: string;
  description: string;
  priceRange: string;
  emoji: string;
  gradientFrom: string;
  gradientTo: string;
  featuredImage: string;
}

export const products: Product[] = [
  // Necklaces - Shell Collection
  {
    id: 1,
    name: "Natural Scallop Shell Pendant",
    description: "Pink and cream scallop shell on white cord",
    price: "$22",
    category: "necklace",
    image: "/product-images/natural-scallop-shell-pendant-white-cord-8c4d2.jpeg",
    emoji: "🐚",
    gradientFrom: "from-pink-50",
    gradientTo: "to-rose-100",
  },
  {
    id: 2,
    name: "Coral Scallop Shell Necklace",
    description: "Wire-wrapped coral shell with gold accents",
    price: "$25",
    category: "necklace",
    image: "/product-images/coral-scallop-shell-gold-wire-necklace-3b9a7.jpeg",
    emoji: "🦪",
    gradientFrom: "from-coral-50",
    gradientTo: "to-orange-100",
  },
  {
    id: 3,
    name: "White Cowrie Shell Pendant",
    description: "Classic cowrie shell with gold cross wire wrap",
    price: "$24",
    category: "necklace",
    image: "/product-images/white-cowrie-shell-gold-cross-wire-9b3a5.jpeg",
    emoji: "🐚",
    gradientFrom: "from-stone-50",
    gradientTo: "to-gray-100",
  },
  {
    id: 4,
    name: "Brown Cone Shell Pendant",
    description: "Natural cone shell with white spots",
    price: "$20",
    category: "necklace",
    image: "/product-images/brown-cone-shell-white-spots-pendant-9a2b6.jpeg",
    emoji: "🏖️",
    gradientFrom: "from-amber-50",
    gradientTo: "to-yellow-100",
  },
  {
    id: 5,
    name: "Pink Striped Fan Shell",
    description: "Delicate fan shell wrapped in copper wire",
    price: "$26",
    category: "necklace",
    image: "/product-images/pink-striped-fan-shell-copper-wire-1e8c7.jpeg",
    emoji: "🌺",
    gradientFrom: "from-pink-50",
    gradientTo: "to-fuchsia-100",
  },
  {
    id: 6,
    name: "Orange Conch Shell Necklace",
    description: "Vibrant conch shell piece with gold wire",
    price: "$24",
    category: "necklace",
    image: "/product-images/orange-conch-shell-gold-wire-necklace-9d5b2.jpeg",
    emoji: "🍊",
    gradientFrom: "from-orange-50",
    gradientTo: "to-amber-100",
  },
  {
    id: 7,
    name: "White Spiral Shell Pendant",
    description: "Elegant spiral shell wrapped in gold",
    price: "$22",
    category: "necklace",
    image: "/product-images/white-spiral-shell-gold-wire-pendant-2c7e4.jpeg",
    emoji: "🌀",
    gradientFrom: "from-zinc-50",
    gradientTo: "to-slate-100",
  },
  {
    id: 8,
    name: "Spotted Limpet Shell",
    description: "Natural limpet shell on pink leather cord",
    price: "$20",
    category: "necklace",
    image: "/product-images/spotted-limpet-shell-pink-leather-cord-8c2e4.jpeg",
    emoji: "🎯",
    gradientFrom: "from-pink-50",
    gradientTo: "to-purple-100",
  },
  {
    id: 9,
    name: "Silver Cockle Shell Pendant",
    description: "Ridged cockle shell with gold wire wrap",
    price: "$23",
    category: "necklace",
    image: "/product-images/silver-cockle-shell-gold-wire-pendant-7d5f2.jpeg",
    emoji: "🥈",
    gradientFrom: "from-gray-50",
    gradientTo: "to-blue-100",
  },
  {
    id: 10,
    name: "White Ribbed Shell Necklace",
    description: "Textured shell on turquoise cord",
    price: "$18",
    category: "necklace",
    image: "/product-images/turquoise-cord-white-ribbed-shell-pendant-7d8e2.jpeg",
    emoji: "🌊",
    gradientFrom: "from-cyan-50",
    gradientTo: "to-blue-100",
  },

  // Necklaces - Stone Collection
  {
    id: 11,
    name: "Wire-Wrapped Pearl Pendant",
    description: "Freshwater pearl in delicate gold wire",
    price: "$28",
    category: "necklace",
    image: "/product-images/wire-wrapped-pearl-pendant-necklace-3e7c4.jpeg",
    emoji: "💎",
    gradientFrom: "from-yellow-50",
    gradientTo: "to-amber-100",
  },
  {
    id: 12,
    name: "Lapis Lazuli Gold Wire Necklace",
    description: "Deep blue lapis stone on white cord",
    price: "$30",
    category: "necklace",
    image: "/product-images/white-cord-necklace-lapis-lazuli-gold-wire-8a2b5.jpeg",
    emoji: "💙",
    gradientFrom: "from-blue-50",
    gradientTo: "to-indigo-100",
  },
  {
    id: 13,
    name: "Amber Sea Glass Pendant",
    description: "Genuine sea glass wrapped in gold wire",
    price: "$26",
    category: "necklace",
    image: "/product-images/amber-sea-glass-pendant-gold-wire-wrap-1c9e4.jpeg",
    emoji: "🟠",
    gradientFrom: "from-amber-50",
    gradientTo: "to-orange-100",
  },
  {
    id: 14,
    name: "Amethyst Crystal Necklace",
    description: "Purple amethyst stone with gold wire",
    price: "$32",
    category: "necklace",
    image: "/product-images/amethyst-pendant-gold-wire-white-cord-7b4a3.jpeg",
    emoji: "💜",
    gradientFrom: "from-purple-50",
    gradientTo: "to-violet-100",
  },
  {
    id: 15,
    name: "Black Obsidian Pendant",
    description: "Polished obsidian on leather cord",
    price: "$28",
    category: "necklace",
    image: "/product-images/black-obsidian-pendant-leather-necklace-9d2f6.jpeg",
    emoji: "⚫",
    gradientFrom: "from-gray-50",
    gradientTo: "to-slate-100",
  },
  {
    id: 16,
    name: "Rose Quartz Triangle",
    description: "Pink quartz wrapped in copper wire",
    price: "$25",
    category: "necklace",
    image: "/product-images/rose-quartz-triangle-copper-wire-pendant-4e8c1.jpeg",
    emoji: "🌸",
    gradientFrom: "from-pink-50",
    gradientTo: "to-rose-100",
  },
  {
    id: 17,
    name: "Dark Stone Gold Wire Pendant",
    description: "Mystery stone wrapped in gold",
    price: "$24",
    category: "necklace",
    image: "/product-images/dark-stone-pendant-gold-wire-leather-6a3b9.jpeg",
    emoji: "🖤",
    gradientFrom: "from-zinc-50",
    gradientTo: "to-gray-100",
  },
  {
    id: 18,
    name: "Pink Stone White Cord Necklace",
    description: "Soft pink stone with gold wire wrap",
    price: "$22",
    category: "necklace",
    image: "/product-images/pink-stone-pendant-gold-wire-white-cord-2f7e5.jpeg",
    emoji: "💗",
    gradientFrom: "from-pink-50",
    gradientTo: "to-fuchsia-100",
  },
  {
    id: 19,
    name: "White Coral Pendant",
    description: "Natural coral piece with gold bail",
    price: "$26",
    category: "necklace",
    image: "/product-images/white-coral-pendant-gold-bail-leather-5f7b3.jpeg",
    emoji: "🏝️",
    gradientFrom: "from-stone-50",
    gradientTo: "to-amber-100",
  },
  {
    id: 20,
    name: "Marbled Cube Pendant",
    description: "Unique marbled stone on black leather",
    price: "$24",
    category: "necklace",
    image: "/product-images/marbled-cube-pendant-black-leather-necklace-5b4a9.jpeg",
    emoji: "🎲",
    gradientFrom: "from-gray-50",
    gradientTo: "to-stone-100",
  },

  // More Shell Necklaces
  {
    id: 21,
    name: "White Shell Pieces Pendant",
    description: "Multiple shell fragments wrapped together",
    price: "$20",
    category: "necklace",
    image: "/product-images/white-shell-pieces-gold-wire-pendant-5e2c8.jpeg",
    emoji: "🤍",
    gradientFrom: "from-gray-50",
    gradientTo: "to-blue-100",
  },
  {
    id: 22,
    name: "Purple Shell Cross Wire Pendant",
    description: "Purple tinted shell with copper cross pattern",
    price: "$23",
    category: "necklace",
    image: "/product-images/purple-shell-copper-cross-wire-pendant-1a7f3.jpeg",
    emoji: "🟣",
    gradientFrom: "from-purple-50",
    gradientTo: "to-pink-100",
  },
  {
    id: 23,
    name: "White Shell Black Leather Necklace",
    description: "Clean white shell with gold wire wrap",
    price: "$21",
    category: "necklace",
    image: "/product-images/white-shell-gold-wire-black-leather-9f3b6.jpeg",
    emoji: "⚪",
    gradientFrom: "from-gray-50",
    gradientTo: "to-slate-100",
  },
  {
    id: 24,
    name: "Orange Striped Shell Necklace",
    description: "Vibrant striped shell with gold wire",
    price: "$22",
    category: "necklace",
    image: "/product-images/orange-striped-shell-gold-wire-necklace-4c5a9.jpeg",
    emoji: "🍑",
    gradientFrom: "from-orange-50",
    gradientTo: "to-pink-100",
  },
  {
    id: 25,
    name: "White Ridged Shell Pendant",
    description: "Textured ridged shell wrapped in gold",
    price: "$20",
    category: "necklace",
    image: "/product-images/white-ridged-shell-gold-wire-pendant-6b2f7.jpeg",
    emoji: "🏔️",
    gradientFrom: "from-stone-50",
    gradientTo: "to-gray-100",
  },
  {
    id: 26,
    name: "Yellow Ridged Shell Necklace",
    description: "Golden yellow shell with wire wrap",
    price: "$22",
    category: "necklace",
    image: "/product-images/yellow-ridged-shell-gold-wire-necklace-8e3c4.jpeg",
    emoji: "🌟",
    gradientFrom: "from-yellow-50",
    gradientTo: "to-amber-100",
  },
  {
    id: 27,
    name: "Red Spotted Shell Pendant",
    description: "Unique spotted shell with gold cross wire",
    price: "$24",
    category: "necklace",
    image: "/product-images/red-spotted-shell-gold-cross-wire-2a9d5.jpeg",
    emoji: "🔴",
    gradientFrom: "from-red-50",
    gradientTo: "to-pink-100",
  },
  {
    id: 28,
    name: "Pink Scallop Copper Wire Necklace",
    description: "Delicate pink scallop with copper accents",
    price: "$21",
    category: "necklace",
    image: "/product-images/pink-scallop-shell-copper-wire-cream-cord-1c4e8.jpeg",
    emoji: "🌷",
    gradientFrom: "from-pink-50",
    gradientTo: "to-orange-100",
  },
  {
    id: 29,
    name: "Pink White Shell Necklace",
    description: "Two-toned shell wrapped in gold wire",
    price: "$23",
    category: "necklace",
    image: "/product-images/pink-white-shell-gold-wire-necklace-3d8f7.jpeg",
    emoji: "🎀",
    gradientFrom: "from-pink-50",
    gradientTo: "to-purple-100",
  },
  {
    id: 30,
    name: "White Textured Coral Pendant",
    description: "Textured coral piece on black leather",
    price: "$25",
    category: "necklace",
    image: "/product-images/white-textured-coral-black-leather-pendant-7e5c2.jpeg",
    emoji: "🪸",
    gradientFrom: "from-gray-50",
    gradientTo: "to-zinc-100",
  },
  {
    id: 31,
    name: "Natural Hole Shell Necklace",
    description: "Shell with natural hole, copper wire wrap",
    price: "$19",
    category: "necklace",
    image: "/product-images/natural-hole-shell-copper-wire-olive-cord-4b9a3.jpeg",
    emoji: "🕳️",
    gradientFrom: "from-olive-50",
    gradientTo: "to-green-100",
  },
  {
    id: 32,
    name: "White Spotted Shell Pendant",
    description: "Spotted pattern shell on black cord",
    price: "$21",
    category: "necklace",
    image: "/product-images/white-spotted-shell-gold-wire-black-cord-8f2d6.jpeg",
    emoji: "⚡",
    gradientFrom: "from-gray-50",
    gradientTo: "to-blue-100",
  },
  {
    id: 33,
    name: "Purple Spotted Shell Necklace",
    description: "Purple and cream spotted shell",
    price: "$23",
    category: "necklace",
    image: "/product-images/purple-spotted-shell-gold-wire-cream-cord-6a3f8.jpeg",
    emoji: "🍇",
    gradientFrom: "from-purple-50",
    gradientTo: "to-pink-100",
  },
  {
    id: 34,
    name: "Textured White Shell Pendant",
    description: "Shell with natural texture patterns",
    price: "$20",
    category: "necklace",
    image: "/product-images/textured-white-shell-natural-holes-pendant-3f7d6.jpeg",
    emoji: "❄️",
    gradientFrom: "from-blue-50",
    gradientTo: "to-gray-100",
  },
  {
    id: 35,
    name: "Striped Limpet Shell Necklace",
    description: "Black and white striped limpet shell",
    price: "$22",
    category: "necklace",
    image: "/product-images/striped-limpet-shell-white-cord-necklace-4a9b3.jpeg",
    emoji: "🦓",
    gradientFrom: "from-gray-50",
    gradientTo: "to-slate-100",
  },
  {
    id: 36,
    name: "Gray Cockle Shell Pendant",
    description: "Ridged gray cockle shell with gold wire",
    price: "$21",
    category: "necklace",
    image: "/product-images/gray-ridged-cockle-shell-gold-wire-2e8c7.jpeg",
    emoji: "🌫️",
    gradientFrom: "from-gray-50",
    gradientTo: "to-blue-100",
  },
  {
    id: 37,
    name: "White Shell Orange Teardrop",
    description: "White shell with orange accent detail",
    price: "$24",
    category: "necklace",
    image: "/product-images/white-shell-orange-teardrop-pendant-6f4d8.jpeg",
    emoji: "💧",
    gradientFrom: "from-orange-50",
    gradientTo: "to-red-100",
  },

  // Bracelets
  {
    id: 38,
    name: "Turquoise Beads Leather Bracelet",
    description: "Bright turquoise with copper accents",
    price: "$12",
    category: "bracelet",
    image: "/product-images/leather-bracelet-turquoise-beads-copper-7c3e1.jpeg",
    emoji: "🌊",
    gradientFrom: "from-cyan-50",
    gradientTo: "to-blue-100",
  },
  {
    id: 39,
    name: "Black Stone Leather Bracelet",
    description: "Single black stone accent on leather",
    price: "$10",
    category: "bracelet",
    image: "/product-images/leather-bracelet-black-stone-accent-9b5a2.jpeg",
    emoji: "⚫",
    gradientFrom: "from-gray-50",
    gradientTo: "to-slate-100",
  },
  {
    id: 40,
    name: "Bright Turquoise Glass Bracelet",
    description: "Vibrant glass beads on leather cord",
    price: "$11",
    category: "bracelet",
    image: "/product-images/leather-bracelet-bright-turquoise-glass-2d8f6.jpeg",
    emoji: "💠",
    gradientFrom: "from-blue-50",
    gradientTo: "to-cyan-100",
  },
  {
    id: 41,
    name: "Rose Quartz Cream Bracelet",
    description: "Pink quartz with cream accent beads",
    price: "$13",
    category: "bracelet",
    image: "/product-images/leather-bracelet-rose-quartz-cream-beads-5f3d7.jpeg",
    emoji: "🌸",
    gradientFrom: "from-pink-50",
    gradientTo: "to-rose-100",
  },

  // Bangle
  {
    id: 42,
    name: "Gold Bangle with Jade Beads",
    description: "Thin gold bangle with green jade accents",
    price: "$18",
    category: "bangle",
    image: "/product-images/gold-bangle-green-jade-beads-a4f2d.jpeg",
    emoji: "💚",
    gradientFrom: "from-emerald-50",
    gradientTo: "to-green-100",
  },
];

// Product categories for the showcase
export const productCategories: ProductCategory[] = [
  {
    id: 1,
    name: "Shell & Pearl Necklaces",
    description: "Wire-wrapped shells, pearls, and beach treasures",
    priceRange: "$18-32",
    emoji: "🐚",
    gradientFrom: "from-blue-50",
    gradientTo: "to-cyan-100",
    featuredImage: "/product-images/natural-scallop-shell-pendant-white-cord-8c4d2.jpeg",
  },
  {
    id: 2,
    name: "Stone & Crystal Pendants",
    description: "Natural stones and crystals wrapped in gold and copper",
    priceRange: "$22-32",
    emoji: "💎",
    gradientFrom: "from-purple-50",
    gradientTo: "to-pink-100",
    featuredImage: "/product-images/amethyst-pendant-gold-wire-white-cord-7b4a3.jpeg",
  },
  {
    id: 3,
    name: "Leather Bracelets & Bangles",
    description: "Handcrafted bracelets with natural stone accents",
    priceRange: "$10-18",
    emoji: "🌊",
    gradientFrom: "from-amber-50",
    gradientTo: "to-orange-100",
    featuredImage: "/product-images/leather-bracelet-turquoise-beads-copper-7c3e1.jpeg",
  },
];

// Helper function to get products by category
export function getProductsByCategory(category: 'necklace' | 'bracelet' | 'bangle') {
  return products.filter(product => product.category === category);
}

// Helper function to get featured products
export function getFeaturedProducts(limit: number = 6) {
  // Return a selection of diverse products
  const featured = [
    products[0],  // Natural Scallop Shell
    products[13], // Amethyst Crystal
    products[37], // Turquoise Bracelet
    products[5],  // Orange Conch Shell
    products[15], // Rose Quartz Triangle
    products[41], // Gold Bangle
  ];
  return featured.slice(0, limit);
}

// Helper function to get product by ID
export function getProductById(id: number) {
  return products.find(product => product.id === id);
}